name: Benchmarks
on:
  push:
    branches:
      - 'main'
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 21.x
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --include=optional

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: npm run benchmark
          token: ${{ secrets.CODSPEED_TOKEN }}
