name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node 21.x
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --include=optional

      - uses: andresz1/size-limit-action@v1
        with:
          skip_step: install
          github_token: ${{ secrets.GITHUB_TOKEN }}
