name: Test deployment
on:
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./website
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - name: Test build website
        run: npm run build
